### ISSUE TITLE
RFE: Add BIND External Forwards config to YAML spec

### ISSUE THREAD

**Issue by kenmoini** [kenmoini/go-zones#18]
Can be added as something like:

```yaml
bind:
  external_forwarders:
  - 1.1.1.1
  - 1.0.0.1
zones:
  - ...
```

This would eliminate the need for an actual container file override
